### ISSUE TITLE
coleta automática de estações por hora

### ISSUE THREAD

**Issue by murilobsd** [lab804/madruga#3]

**Comment by murilobsd** [comment]
## TODO

- [x] Instalação celery
- [x] Configuração
- [x] Função para disparo a cada 1h20
- [x] Função para agrupamento das tasks disparadas
- [x] Campo updated_at no modelo da estação
- [ ] Manage método para coletar dados 
- [x] Instalacao do Mongo
- [x] Configuração Mongo
- [x] Indexação
- [x] Variáveis de ambiente

**Comment by murilobsd** [comment]
![screenshot from 2018-04-07 17-44-35](https://user-images.githubusercontent.com/3185376/38460188-609c9c66-3a8b-11e8-969c-5c712aeafdb5.png)
